import { Inter } from 'next/font/google'
import './globals.css'
import { GlobalProvider } from '@/context/global'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <GlobalProvider>
      <html lang="en">
      <body className={inter.className}>
         <nav className='bg-orange-100 p-3 border'>
           <div className='flex flex-row '>
           <h1 className='font-bold text-lg'>GIPHY</h1>
           
           </div>
           
         </nav>
        {children}</body>
    </html>
    </GlobalProvider>
    
  )
}
